name: renovate-config:validate

on:
  push:
    paths:
      - ".github/**"
      - "default.json"
      - "ignore-paths.json"
      - "casks.json"
    branches:
      - main
  pull_request:
    paths:
      - ".github/**"
      - "default.json"
      - "ignore-paths.json"
      - "casks.json"

jobs:
  validate:
    uses: ./.github/workflows/validator.yaml
    with:
      config_files: ".github/renovate.json default.json ignore-paths.json casks.json"
